# Site settings
title: rcyou.co
author: Ryan Young
email: ryoung@mail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rcyou.co" # the base hostname & protocol for your site
# social media links
twitter: rcyou
dribbble: rcyou
github:  rcyou
pinterest: rcyou
codepen: rcyou
linkedin: rcyou

# Build settings
markdown: kramdown
