# Site settings
title: rcyou.co
author: Ryan Young
email: ryoung@mail.com
description: > # this means to ignore newlines until "baseurl:"
  Ryan Young is a web designer and front-end developer in Des Moines, Iowa. He currently works as a project lead for Visionary Services, a web design and development firm in downtown Des Moines’ historic East Village neighborhood.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rcyou.co" # the base hostname & protocol for your site
# social media links
twitter: rcyou
dribbble: rcyou
github:  rcyou
pinterest: rcyou
codepen: rcyou
linkedin: rcyou

# Build settings
markdown: kramdown
